export const objects = [
  {
    title: 'Расцветай на Красном',
    description: 'Расцветай',
    src: '/static/images/cards/1.jpeg',
    price: 'от 5.550.000',
  },
  {
    title: 'Мылзавод',
    description: 'Брусника',
    src: '/static/images/cards/2.jpeg',
    price: 'от 4.870.000',
  },
  {
    title: 'Сакура Парк',
    description: 'Расцветай',
    src: '/static/images/cards/3.jpeg',
    price: 'от 5.300.000',
  },
  {
    title: 'ALMOND',
    description: 'Расцветай',
    src: '/static/images/cards/4.jpeg',
    price: 'от 8.500.000',
  },
  {
    title: 'Европейский Берег',
    description: 'Брусника',
    src: '/static/images/cards/5.jpeg',
    price: 'от 5.750.000',
  },
  {
    title: 'Пшеница',
    description: 'Брусника',
    src: '/static/images/cards/6.jpeg',
    price: 'от 5.500.000',
  },
  {
    title: 'Тайгинский Парк',
    description: 'ГК «КПД-Газстрой»',
    src: '/static/images/cards/7.jpeg',
    price: 'от 3.470.000',
  },
  {
    title: 'СКАНДИА. В Кедровом.',
    description: 'Скандиа Девелопмент',
    src: '/static/images/cards/8.jpeg',
    price: 'от 4.750.000',
  },
  {
    title: 'ЖК Никольский парк',
    description: 'ГК ХИММЕТАЛЛ',
    src: '/static/images/cards/9.jpeg',
    price: 'от 3.150.000',
  },
  {
    title: 'ЖК Ясный Берег',
    description: 'ООО СЗ «АКВА СИТИ»',
    src: '/static/images/cards/10.jpeg',
    price: 'от 4.100.000',
  },
  {
    title: 'СЗ НОБЕЛЬ',
    description: 'Группа компании НОВЫЙ МИР',
    src: '/static/images/cards/11.jpeg',
    price: 'от 4.700.000',
  },
  {
    title: 'Квартал на Декабристов',
    description: 'БРУСНИКА',
    src: '/static/images/cards/12.jpeg',
    price: 'от 10.250.000',
  },
  {
    title: 'Жилой дом ZOE',
    description: 'СЗ Мегатрейд',
    src: '/static/images/cards/13.jpeg',
    price: 'от 5.900.000',
  },
];
